baseURL = 'https://vovavasylyna.com'
languageCode = 'en-us'
title = 'Volodymyr Vasylyna'
theme = 'simplica'
paginate = '9999'

[params]
description = "A personal blog about development, books, work, digital minimalism, and more."
subtitle = ""

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.9

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[frontmatter]
author = "Volodymyr Vasylyna"

